AppBundle\Entity\Historial:
    type: entity
    table: Historial
    indexes:
        fk_Historial_Programa_idx:
            columns:
                - Programa_id
        fk_Historial_Alumno1_idx:
            columns:
                - Alumno_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        anoIngreso:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ano_ingreso
        semestreIngreso:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: semestre_ingreso
        semestresSuspension:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: semestres_suspension
        estudianteTitulo:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: estudiante_titulo
        anoMatricula:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '2010'
            column: ano_matricula
    manyToOne:
        alumno:
            targetEntity: Alumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Alumno_id:
                    referencedColumnName: id
            orphanRemoval: false
        programa:
            targetEntity: Programa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Programa_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
