AppBundle\Entity\Programa:
    type: entity
    table: Programa
    uniqueConstraints:
        codigo_UNIQUE:
            columns:
                - codigo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        horario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        sede:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        tipo:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        duracion:
            type: integer
            nullable: true
            options:
                unsigned: false
        duracionTitulo:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: duracion_titulo
    lifecycleCallbacks: {  }
